{ AltiumVerify.pas

  On-site verification that .PcbLib / .SchLib files generated by altium-designer-mcp
  open cleanly in a real Altium Designer install — the ground-truth check that the
  independent pyaltiumlib oracle only approximates.

  It reads a request file (one absolute library path per line) from the bridge
  directory, opens each library in Altium, and writes a JSON array of results to the
  response file. The PowerShell wrapper (..\..\Verify-Libraries.ps1) writes the request,
  launches this via Altium's RunScript CLI, and polls for the response.

  The RunScript launch mechanism and the file-based request/response bridge are
  adapted from coffeenmusic/altium-mcp (MIT) — https://github.com/coffeenmusic/altium-mcp

  Run via:
    X2.EXE -RScriptingSystem:RunScript(ProjectName="...\AltiumVerify.PrjScr"^|ProcName="AltiumVerify>Run")

  Limitation: a genuinely corrupt library can make Altium raise a modal
  "catastrophic failure" dialog that blocks the script (the try/except below only
  catches non-modal errors). That is itself a useful signal — if the wrapper times
  out waiting for the response, the file did not open. }

const
    BRIDGE_DIR = 'C:\Users\Public\altium_designer_mcp\';
    REPLACEALL = 1; // StringReplace flags value for rfReplaceAll (DelphiScript)

// Escapes a string for embedding in JSON (paths contain backslashes).
function JsonEscape(const S : String) : String;
var
    i, C : Integer;
begin
    Result := '';
    for i := 1 to Length(S) do
    begin
        C := Ord(S[i]);
        if (C > 126) or (C < 32) then Result := Result + '\u' + IntToHex(C, 4)
        else if S[i] = '\' then Result := Result + '\\'
        else if S[i] = '"' then Result := Result + '\"'
        else Result := Result + S[i];
    end;
end;


{ Returns the currently-open library's component names as a JSON array. Altium
  resolves these itself, so they are ground truth for what it actually parsed —
  "opened" alone does not prove a component is reachable or that its name
  survived. Returns [] for a kind with no reachable library. }
function ComponentNames(const Kind : String) : String;
var
    PcbLib  : IPCB_Library;
    SchLib  : ISch_Lib;
    SchIter : ISch_Iterator;
    SchComp : ISch_Component;
    PcbComp : IPCB_LibComponent;
    PcbIter : IPCB_LibraryIterator;
    First   : Boolean;
begin
    Result := '[';
    First  := True;
    try
        if Kind = 'PCBLIB' then
        begin
            PcbLib := PCBServer.GetCurrentPCBLibrary;
            if PcbLib <> nil then
            begin
                PcbIter := PcbLib.LibraryIterator_Create;
                PcbIter.SetState_FilterAll;
                PcbComp := PcbIter.FirstPCBObject;
                while PcbComp <> nil do
                begin
                    if not First then Result := Result + ',';
                    Result := Result + '"' + JsonEscape(PcbComp.Name) + '"';
                    First := False;
                    PcbComp := PcbIter.NextPCBObject;
                end;
                PcbLib.LibraryIterator_Destroy(PcbIter);
            end;
        end
        else if Kind = 'SCHLIB' then
        begin
            SchLib := SchServer.GetCurrentSchDocument;
            if SchLib <> nil then
            begin
                SchIter := SchLib.SchLibIterator_Create;
                SchIter.AddFilter_ObjectSet(MkSet(eSchComponent));
                SchComp := SchIter.FirstSchObject;
                while SchComp <> nil do
                begin
                    if not First then Result := Result + ',';
                    Result := Result + '"' + JsonEscape(SchComp.LibReference) + '"';
                    First := False;
                    SchComp := SchIter.NextSchObject;
                end;
                SchLib.SchIterator_Destroy(SchIter);
            end;
        end;
    except
    end;
    Result := Result + ']';
end;

procedure Run;
var
    RequestFile, ResponseFile : String;
    Requests, Response : TStringList;
    Json, Path, Ext, Kind, Detail, Names : String;
    i, Emitted : Integer;
    Doc : IServerDocument;
    Opened : Boolean;
begin
    RequestFile  := BRIDGE_DIR + 'verify_request.txt';
    ResponseFile := BRIDGE_DIR + 'verify_response.json';
    if not DirectoryExists(BRIDGE_DIR) then ForceDirectories(BRIDGE_DIR);

    Requests := TStringList.Create;
    Response := TStringList.Create;
    try
        if not FileExists(RequestFile) then
        begin
            Response.Text := '{"error":"no request file at ' + JsonEscape(RequestFile) + '"}';
            Response.SaveToFile(ResponseFile);
            Exit;
        end;
        Requests.LoadFromFile(RequestFile);

        Json := '[';
        Emitted := 0;
        for i := 0 to Requests.Count - 1 do
        begin
            Path := Trim(Requests[i]);
            if Path = '' then Continue;

            Ext := UpperCase(ExtractFileExt(Path));
            if      Ext = '.PCBLIB' then Kind := 'PCBLIB'
            else if Ext = '.SCHLIB' then Kind := 'SCHLIB'
            else                         Kind := '';

            Opened := False;
            Names  := '[]';
            Detail := '';

            if not FileExists(Path) then
                Detail := 'file not found'
            else if Kind = '' then
                Detail := 'unsupported extension (expected .PcbLib or .SchLib)'
            else
            begin
                try
                    Doc := Client.OpenDocument(Kind, Path);
                    if Doc <> nil then
                    begin
                        Client.ShowDocument(Doc);
                        Opened := True;
                        Detail := 'opened';
                        Names := ComponentNames(Kind);
                        // Leave the document open so it stays visible for inspection
                        // (e.g. to check a footprint's 3D body).
                    end
                    else
                        Detail := 'Altium OpenDocument returned nil (could not parse)';
                except
                    Opened := False;
                    Detail := 'exception while opening (likely catastrophic failure)';
                end;
            end;

            if Emitted > 0 then Json := Json + ',';
            Json := Json + '{"file":"' + JsonEscape(Path) + '","kind":"' + Kind + '","opened":';
            if Opened then Json := Json + 'true' else Json := Json + 'false';
            Json := Json + ',"detail":"' + JsonEscape(Detail) + '"';
            // The component names Altium itself resolved. "Opened" only proves the
            // file parses; a name check proves the components are reachable and
            // their text survived, which is what a round-trip claim needs.
            Json := Json + ',"components":' + Names + '}';
            Inc(Emitted);
        end;
        Json := Json + ']';

        Response.Text := Json;
        Response.SaveToFile(ResponseFile);
    finally
        Requests.Free;
        Response.Free;
    end;
end;
